import fs from 'fs'
import matter from 'gray-matter'
import Link from 'next/link'
import path from 'path'
import Layout from '../components/Layout'
import { postFilePaths, POSTS_PATH } from '../utils/mdxUtils'

import styled from "@emotion/styled";
import CardGrid from "../app/components/base/CardGrid";
import Card from "../app/components/base/Card";
import HeroCard from "../app/components/base/HeroCard";
import HeroImage from "../app/components/base/HeroImage";
import ExternalCTA from "../app/components/base/ExternalCTA";
import Banner from "../app/components/base/Banner";
import LogoLinks from "../app/components/base/LogoLinks";
import FooterCTA from "../app/components/base/FooterCTA";
import IFrame from "../app/components/base/IFrame";
import { H3 } from "../app/components/base/Typography";
import { HEADLINE_TEXT } from "../app/components/colors";
import { breakDown } from "../app/components/breakpoints";
import dropInsHeroImage from "../assets/images/content-images/hero-image-drop-ins.png";
import guideIcon from "../assets/images/content-images/content-icons/guides-icon.svg";
import conceptIcon from "../assets/images/content-images/content-icons/concepts-icon.svg";
import apiReferenceIcon from "../assets/images/content-images/content-icons/api-reference-icon.svg";
import demoAppIcon from "../assets/images/content-images/content-icons/dwolla-demo-app.svg";
import developerCommunityIcon from "../assets/images/content-images/content-icons/developer-community-icon.svg";
import { ReactComponent as CaretRightIcon } from "../assets/images/component-icons/caret-right.svg";
// Language logos in gray and in color
import phpColor from "../assets/images/content-images/content-icons/language-logos/php-logo.svg";
import phpGray from "../assets/images/content-images/content-icons/language-logos/php-logo-gray.svg";
import pythonColor from "../assets/images/content-images/content-icons/language-logos/python-logo.svg";
import pythonGray from "../assets/images/content-images/content-icons/language-logos/python-logo-gray.svg";
import rubyColor from "../assets/images/content-images/content-icons/language-logos/ruby-logo.svg";
import rubyGray from "../assets/images/content-images/content-icons/language-logos/ruby-logo-gray.svg";
import cSharpColor from "../assets/images/content-images/content-icons/language-logos/c-sharp-logo.svg";
import cSharpGray from "../assets/images/content-images/content-icons/language-logos/c-sharp-logo-gray.svg";
import kotlinColor from "../assets/images/content-images/content-icons/language-logos/kotlin-logo.svg";
import kotlinGray from "../assets/images/content-images/content-icons/language-logos/kotlin-logo-gray.svg";
import nodeColor from "../assets/images/content-images/content-icons/language-logos/node-js-logo.svg";
import nodeGray from "../assets/images/content-images/content-icons/language-logos/node-js-logo-gray.svg";
// Partner logos in gray and in color
import quickbooksColor from "../assets/images/content-images/content-icons/partner-logos/quickbooks-logo.svg";
import quickbooksGray from "../assets/images/content-images/content-icons/partner-logos/quickbooks-logo-gray.svg";
import plaidColor from "../assets/images/content-images/content-icons/partner-logos/plaid-logo.svg";
import plaidGray from "../assets/images/content-images/content-icons/partner-logos/plaid-logo-gray.svg";
import siftColor from "../assets/images/content-images/content-icons/partner-logos/sift-logo.svg";
import siftGray from "../assets/images/content-images/content-icons/partner-logos/sift-logo-gray.svg";
import slackColor from "../assets/images/content-images/content-icons/partner-logos/slack-logo.svg";
import slackGray from "../assets/images/content-images/content-icons/partner-logos/slack-logo-gray.svg";

export default function Index({ posts }) {
  return (
    <Layout>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{' '}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link
              as={`/posts/${post.filePath.replace(/\.mdx?$/, '')}`}
              href={`/posts/[slug]`}
            >
              <a>{post.data.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  )
}

export function getStaticProps() {
  const posts = postFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(POSTS_PATH, filePath))
    const { content, data } = matter(source)

    return {
      content,
      data,
      filePath,
    }
  })

  return { props: { posts } }
}